<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $phone
 * @property string $twitter_handle
 * 
 * @method string  getName()           Returns the current record's "name" value
 * @method string  getPhone()          Returns the current record's "phone" value
 * @method string  getTwitterHandle()  Returns the current record's "twitter_handle" value
 * @method Contact setName()           Sets the current record's "name" value
 * @method Contact setPhone()          Sets the current record's "phone" value
 * @method Contact setTwitterHandle()  Sets the current record's "twitter_handle" value
 * 
 * @package    address_book
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('twitter_handle', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}